export const PolicyManagerAbi = [
  {
    type: 'function',
    name: 'buyPolicy',
    inputs: [
      { name: 'hazard', type: 'uint8' },
      { name: 'durationDays', type: 'uint256' },
      { name: 'maxCoverage', type: 'uint256' },
      { name: 'premium', type: 'uint256' },
      { name: 'triggerThreshold', type: 'int256' },
      { name: 'receiver', type: 'address' },
      { name: 'lat', type: 'int32' },
      { name: 'lon', type: 'int32' },
    ],
    outputs: [{ name: 'id', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'policies',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'hazard', type: 'uint8' },
      { name: 'start', type: 'uint40' },
      { name: 'end', type: 'uint40' },
      { name: 'lat', type: 'int32' },
      { name: 'lon', type: 'int32' },
      { name: 'maxCoverage', type: 'uint256' },
      { name: 'premium', type: 'uint256' },
      { name: 'triggerThreshold', type: 'int256' },
      { name: 'paid', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'holderOf',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nextId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'asset',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'vault',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalActiveCoverage',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hazardNames',
    inputs: [{ name: '', type: 'uint8' }],
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hazardTriggerAbove',
    inputs: [{ name: '', type: 'uint8' }],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'PolicyPurchased',
    inputs: [
      { name: 'policyId', type: 'uint256', indexed: true },
      { name: 'holder', type: 'address', indexed: true },
      { name: 'hazard', type: 'uint8', indexed: false },
      { name: 'start', type: 'uint256', indexed: false },
      { name: 'end', type: 'uint256', indexed: false },
      { name: 'maxCoverage', type: 'uint256', indexed: false },
      { name: 'triggerThreshold', type: 'int256', indexed: false },
      { name: 'lat', type: 'int32', indexed: false },
      { name: 'lon', type: 'int32', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PayoutTriggered',
    inputs: [
      { name: 'policyId', type: 'uint256', indexed: true },
      { name: 'holder', type: 'address', indexed: true },
      { name: 'observedValue', type: 'int256', indexed: false },
      { name: 'requestedPayout', type: 'uint256', indexed: false },
      { name: 'actualPayout', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
] as const
